config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :interviews

      resources :job_applications

      resources :companies

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :interviews
  resources :job_applications
  resources :companies
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/interviews_controller.rb
class Api::V1::InterviewsController < Api::V1::GraphitiController
  def index
    interviews = InterviewResource.all(params)
    respond_with(interviews)
  end

  def show
    interview = InterviewResource.find(params)
    respond_with(interview)
  end

  def create
    interview = InterviewResource.build(params)

    if interview.save
      render jsonapi: interview, status: :created
    else
      render jsonapi_errors: interview
    end
  end

  def update
    interview = InterviewResource.find(params)

    if interview.update_attributes
      render jsonapi: interview
    else
      render jsonapi_errors: interview
    end
  end

  def destroy
    interview = InterviewResource.find(params)

    if interview.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: interview
    end
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: %i[show edit update destroy]

  def index
    @q = Interview.ransack(params[:q])
    @interviews = @q.result(distinct: true).includes(:job_application,
                                                     :applicant, :company).page(params[:page]).per(10)
  end

  def show; end

  def new
    @interview = Interview.new
  end

  def edit; end

  def create
    @interview = Interview.new(interview_params)

    if @interview.save
      message = "Interview was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @interview, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @interview.update(interview_params)
      redirect_to @interview, notice: "Interview was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @interview.destroy
    message = "Interview was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to interviews_url, notice: message
    end
  end

  private

  def set_interview
    @interview = Interview.find(params[:id])
  end

  def interview_params
    params.require(:interview).permit(:starts_on, :round, :completed,
                                      :job_application_id)
  end
end

app/views/interviews/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Interview #<%= interview.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Starts on</dt>
      <dd><%= interview.starts_on %></dd>

      <dt>Round</dt>
      <dd><%= interview.round %></dd>

      <dt>Completed</dt>
      <dd><%= interview.completed %></dd>

      <dt>Job application</dt>
      <dd>
        <% if @interview.job_application.present? %>
          <%= link_to interview.job_application, interview.job_application %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back interview, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_interview_url(interview), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to interview, method: :delete, data: { confirm: "Do you really want to delete this interview?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(interview.updated_at) %> ago
  </div>
</div>

app/views/interviews/_form.html.erb
<% was_validated = interview.errors.any? %>

<%= form_with(model: interview, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% starts_on_class = "form-control" %>
    <% starts_on_was_invalid = interview.errors.include?(:starts_on) %>

    <% if was_validated %>
      <% if starts_on_was_invalid %>
        <% starts_on_class << " is-invalid" %>
      <% else %>
        <% starts_on_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :starts_on %>
    <%= f.datetime_select :starts_on, class: starts_on_class, placeholder: "Enter starts on" %>
    <% if starts_on_was_invalid %>
      <% interview.errors.full_messages_for(:starts_on).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% round_class = "form-control" %>
    <% round_was_invalid = interview.errors.include?(:round) %>

    <% if was_validated %>
      <% if round_was_invalid %>
        <% round_class << " is-invalid" %>
      <% else %>
        <% round_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :round %>
    <%= f.number_field :round, class: round_class, placeholder: "Enter round" %>
    <% if round_was_invalid %>
      <% interview.errors.full_messages_for(:round).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% completed_class = "form-check-input" %>
    <% completed_was_invalid = interview.errors.include?(:completed) %>

    <% if was_validated %>
      <% if completed_was_invalid %>
        <% completed_class << " is-invalid" %>
      <% else %>
        <% completed_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :completed, class: "form-check-label" do %>
      <%= f.check_box :completed, class: completed_class %> Completed
    <% end %>
    <% if completed_was_invalid %>
      <% interview.errors.full_messages_for(:completed).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% job_application_class = "form-control" %>
    <% job_application_was_invalid = interview.errors.include?(:job_application) %>

    <% if was_validated %>
      <% if job_application_was_invalid %>
        <% job_application_class << " is-invalid" %>
      <% else %>
        <% job_application_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :job_application_id %>
    <%= f.collection_select :job_application_id, JobApplication.all, :id, :to_s, {}, class: "form-control" %>
    <% if job_application_was_invalid %>
      <% interview.errors.full_messages_for(:job_application).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/interviews/_interview_applicant.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Applicant
  </div>

  <ul class="list-group list-group-flush">
    <% @interview.applicant.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/interviews/_interviews_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "interviews_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :starts_on, "Starts on" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='starts_ongteqPicker' data-target-input="nearest">
          <%= f.text_field :starts_on_gteq, :class => "form-control datetimepicker-input", :placeholder => "Starts on greater than or equal to", :data => {:target => '#starts_ongteqPicker'} %>
          <div class="input-group-append" data-target='#starts_ongteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='starts_onlteqPicker' data-target-input="nearest">
          <%= f.text_field :starts_on_lteq, :class => "form-control datetimepicker-input", :placeholder => "Starts on less than or equal to", :data => {:target => '#starts_onlteqPicker'} %>
          <div class="input-group-append" data-target='#starts_onlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#starts_ongteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#starts_onlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#starts_ongteqPicker').on("dp.change", function (e) {
              $('#starts_onlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#starts_onlteqPicker').on("dp.change", function (e) {
              $('#starts_ongteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :completed_eq, "Completed" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :completed_eq, "1", checked: ((params[:q] && params[:q][:completed_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :completed_eq, "0", checked: ((params[:q] && params[:q][:completed_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :completed_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :round, "Round" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :round_gteq, :class => "form-control", :placeholder => "Round greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :round_lteq, :class => "form-control", :placeholder => "Round less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :job_application_title_cont, "Job application title contains" %>
    <%= f.text_field :job_application_title_cont, :class => "form-control", :placeholder => "Job application title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :applicant_email_cont, "Applicant email contains" %>
    <%= f.text_field :applicant_email_cont, :class => "form-control", :placeholder => "Applicant email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :company_name_cont, "Company name contains" %>
    <%= f.text_field :company_name_cont, :class => "form-control", :placeholder => "Company name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/interviews" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#interviews_filters">
  Show filters
</a>

app/views/interviews/_list_item.html.erb
<%= link_to interview, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= interview %>
    <small class="text-muted">
      <%= time_ago_in_words(interview.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/interviews/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Interview #<%= @interview.id %>
      </h2>

      <div class="card-body">
        <%= render "form", interview: @interview %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/interviews/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Interviews

      <%= link_to new_interview_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "interviews/interviews_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Interviews

        <%= link_to new_interview_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @interviews, partial: "list_item", as: :interview %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @interviews, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/interviews/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Interview
      </h2>

      <div class="card-body">
        <%= render "form", interview: @interview %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/interviews/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @interview, partial: "card", as: :interview %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "interviews/interview_applicant" %>
  </div>
</div>