config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :interviews

      resources :job_applications

      resources :companies

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "companies#index"
  resources :interviews
  resources :job_applications
  resources :companies
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  # Direct associations

  has_many   :job_applications,
             dependent: :nullify

  # Indirect associations

  has_many   :interviews,
             through: :job_applications,
             source: :interviews

  has_many   :interviewed_applicants,
             through: :interviews,
             source: :applicant

  # Validations

  validates :name, presence: true

  validates :sector, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::GraphitiController
  def index
    companies = CompanyResource.all(params)
    respond_with(companies)
  end

  def show
    company = CompanyResource.find(params)
    respond_with(company)
  end

  def create
    company = CompanyResource.build(params)

    if company.save
      render jsonapi: company, status: :created
    else
      render jsonapi_errors: company
    end
  end

  def update
    company = CompanyResource.find(params)

    if company.update_attributes
      render jsonapi: company
    else
      render jsonapi_errors: company
    end
  end

  def destroy
    company = CompanyResource.find(params)

    if company.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: company
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result(distinct: true).includes(:job_applications,
                                                    :interviewed_applicants, :interviews).page(params[:page]).per(10)
  end

  def show
    @job_application = JobApplication.new
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: "Company was successfully created."
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: "Company was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :sector)
  end
end

app/views/companies/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Company #<%= company.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= company.name %></dd>

      <dt>Sector</dt>
      <dd><%= company.sector %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back company, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_company_url(company), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to company, method: :delete, data: { confirm: "Do you really want to delete this company?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(company.updated_at) %> ago
  </div>
</div>

app/views/companies/_companies_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "companies_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :sector_cont, "Sector contains" %>
    <%= f.text_field :sector_cont, :class => "form-control", :placeholder => "Sector contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :job_applications_title_cont, "Job applications title contains" %>
    <%= f.text_field :job_applications_title_cont, :class => "form-control", :placeholder => "Job applications title contains" %>
  </div>

  <div class="form-group">
    <%= f.label :interviewed_applicants_email_cont, "Interviewed applicants email contains" %>
    <%= f.text_field :interviewed_applicants_email_cont, :class => "form-control", :placeholder => "Interviewed applicants email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :starts_on, "Interview Starts on" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='interviewsgteqstarts_onPicker' data-target-input="nearest">
          <%= f.text_field :interviews_starts_on_gteq, :class => "form-control datetimepicker-input", :placeholder => "Interview Starts on greater than or equal to", :data => {:target => '#interviewsgteqstarts_onPicker'} %>
          <div class="input-group-append" data-target='#interviewsgteqstarts_onPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='interviewslteqstarts_onPicker' data-target-input="nearest">
          <%= f.text_field :interviews_starts_on_lteq, :class => "form-control datetimepicker-input", :placeholder => "Interview Starts on less than or equal to", :data => {:target => '#interviewslteqstarts_onPicker'} %>
          <div class="input-group-append" data-target='#interviewslteqstarts_onPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#interviewsgteqstarts_onPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#interviewslteqstarts_onPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#interviewsgteqstarts_onPicker').on("dp.change", function (e) {
              $('#interviewslteqstarts_onPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#interviewslteqstarts_onPicker').on("dp.change", function (e) {
              $('#interviewsgteqstarts_onPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/companies" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#companies_filters">
  Show filters
</a>

app/views/companies/_company_interviewed_applicants.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Interviewed Applicants
  </div>

  <ul class="list-group list-group-flush">
    <% @company.interviewed_applicants.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/companies/_company_job_applications.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Job Applications

    <a data-toggle="collapse" href="#company_job_applications_new_form">
      Add job application
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @company.job_applications.each do |job_application| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to job_application, job_application %>

        <% if current_user == job_application.user %>
          <%= link_to job_application, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="company_job_applications_new_form">
        <%= render partial: "companies/company_job_applications_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/companies/_company_job_applications_new_form.html.erb
<%= form_with(model: @job_application, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>

    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :due_on %>
    <%= f.datetime_select :due_on, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>

    <%= f.text_field :status, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.hidden_field :company_id, value: @company.id %>

  <%= f.submit "Create job application", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/companies/_form.html.erb
<% was_validated = company.errors.any? %>

<%= form_with(model: company, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = company.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% company.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% sector_class = "form-control" %>
    <% sector_was_invalid = company.errors.include?(:sector) %>

    <% if was_validated %>
      <% if sector_was_invalid %>
        <% sector_class << " is-invalid" %>
      <% else %>
        <% sector_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :sector %>
    <%= f.text_field :sector, class: sector_class, placeholder: "Enter sector" %>
    <% if sector_was_invalid %>
      <% company.errors.full_messages_for(:sector).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/companies/_list_item.html.erb
<%= link_to company, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= company %>
    <small class="text-muted">
      <%= time_ago_in_words(company.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/companies/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Company #<%= @company.id %>
      </h2>

      <div class="card-body">
        <%= render "form", company: @company %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Companies

      <%= link_to new_company_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "companies/companies_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Companies

        <%= link_to new_company_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @companies, partial: "list_item", as: :company %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @companies, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Company
      </h2>

      <div class="card-body">
        <%= render "form", company: @company %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @company, partial: "card", as: :company %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "companies/company_job_applications" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "companies/company_interviewed_applicants" %>
  </div>
</div>